### ISSUE TITLE
Error on creating domain and route

### ISSUE THREAD

**Issue by suchitagarwal-okta** [wgebis/terraform-provider-mailgun#21]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v1.0.5

### Affected Resource(s)
Please list the resources as a list, for example:
- mailgun_domain

### Terraform Configuration Files
```hcl
resource "mailgun_domain" "domain" {
  name     = "test.askspoke-local.com"
  wildcard = true
}

# Create a new Mailgun route
resource "mailgun_route" "route" {
  priority   = "0"
  expression = "match_recipient('.*@.*.test.example.com')"
  actions = [
    "forward(https://webhooks.test.example.com/webhooks/email)"
  ]
}

```

### Debug Output
```
Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.mailgun.mailgun_route.route, provider "provider["registry.terraform.io/wgebis/mailgun"]" produced an unexpected new
│ value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by wgebis** [comment]
Hi @suchitagarwal-okta, does it still exist in v1.0.7 of terraform?
