### ISSUE TITLE
Mailgun is going to remove `smtp_password` parameter in GET `/domains` and `/domains/` API calls. 

### ISSUE THREAD

**Issue by chaliy** [wgebis/terraform-provider-mailgun#22]
Hello sorry for non compliant issue reporting. 

Mailgun is going to remove `smtp_password` parameter in GET `/domains` and `/domains/` API calls. It seems like it is in use for the `resource_mailgun_domain` for [change detection](https://github.com/wgebis/terraform-provider-mailgun/blob/master/mailgun/resource_mailgun_domain.go#L151). It sounds like if it will not fail, it will constantly generate changes. 

More details: https://help.mailgun.com/hc/en-us/articles/4405121167387

**Comment by wgebis** [comment]
Hi @chaliy 
yes, it's correct I'm aware of it. `smtp_password` is still available at time of creation. To avoid generating changes you can mark it after creation as ignored. 
Let me know if it makes sense for you. I don't have a better solution at the moment 😢 .
Thanks,
W

**Comment by chaliy** [comment]
Hello @wgebis , in my case I think we will just remove setting `smtp_password` at all, so most likely we have workaround.
