### ISSUE TITLE
mailgun_domain always updated but smtp_password hasn't changed

### ISSUE THREAD

**Issue by ffabing** [wgebis/terraform-provider-mailgun#26]
### Terraform Version

```
0.13.4
```

### Affected Resource(s)
- mailgun_domain

### Expected Behavior
Sending same smtp_password to mailgun_domain should not update resource.

### Actual Behavior
```
resource "mailgun_domain" "default" {
  name          = var.domain
  region        = "eu"
  spam_action   = "disabled"
  dkim_key_size = 2048
  smtp_password = var.password
}
```
terraform plan :
```
# module.mailgun.mailgun_domain.default will be updated in-place
  ~ resource "mailgun_domain" "default" {
[...]
+ smtp_password     = "[MASKED]"
[...]
```
(this is the only change showed by terraform plan)

We're setting mailgun_domain password with var.password (it doesn't change when doing several terraform apply).
Since November 1st, mailgun domain API doesn't display smtp_password field : https://help.mailgun.com/hc/en-us/articles/4405121167387-FAQ-The-Coming-Domains-API-Change-To-Remove-The-SMTP-Password-On-November-1-2021.
It could be a side effect that force resource to be update since the field isn't returned by the API ?

**Comment by wgebis** [comment]
@ffabing 
Hi, yes this is consequence of Mailgun API. The good trade-off is marking the pass as ignored after creation:
```
  lifecycle {
    ignore_changes = [
      smtp_password
    ]
  }
 ```

**Comment by ffabing** [comment]
Hi @wgebis, thanks for your response

Ideally, we would make a schedule job to renew our smtp password, and then apply the changes.
If we add the ignore_changes attribute, the resource will not be updated with the new password.
Do you have an idea how we could handle that case please ?
The only solution that comes to me is to separate our actual state to isolate the mailgun resources, and then only apply when smtp_password changes.

**Comment by wgebis** [comment]
Due to lack of returning secrets from API, I don't see any option do compare the secrets. 
Every resource attribute is comparing:  value from tf state and the value from the tf file, if API is not able to return current value this comparison always reports a change. 
You should consider using `mailgun_domain_credentials` resource, it obeys the same rules, but you might simple destroy and create the new resource each time you want to reset the password.

**Comment by ffabing** [comment]
Thanks we will see how to get it to work, I close the issue
