### ISSUE TITLE
Support smtp_password updates

### ISSUE THREAD

**Issue by arnisoph** [wgebis/terraform-provider-mailgun#5]
https://github.com/wgebis/terraform-provider-mailgun/blob/master/mailgun/resource_mailgun_domain.go#L52

The API supports in-place updates of SMTP credentials. No need to re-create the mailgun_domain from scratch.

https://documentation.mailgun.com/en/latest/api-domains.html#domains

**Comment by wgebis** [comment]
Hi there! 
Thanks @arnisoph for creating the ticket ! 
API doc says that we have only PUT and DELETE options for domains objects - there is no possible to modify the domain via API. 
Fortunately it is possible to create smtp credentials objects without touching the domain itself. It requires implement support for that objects in the current provider implementation. 
I mark the ticket as an enhancement label.
Thanks,
W

**Comment by arnisoph** [comment]
You can change existing smtp credentials, I've just done it today:

```
$ curl -vs -X PUT --user 'api:KEY' https://api.eu.mailgun.net/v3/domains/domain.de/credentials/postmaster@domain.de -F password=foo42
```

**Comment by wgebis** [comment]
Yes, it seems to work for the default smtp account, so looks that it could be used in this case. I'll look at it during further plugin development. Let's leave the ticket as open for now.

**Comment by wgebis** [comment]
Hi @arnisoph, I have bumped v0.5.4 with support for updating smtp password. Let me know if it works for you 👍 .
