### ISSUE TITLE
I can't create the dns records at the same run I create the domain

### ISSUE THREAD

**Issue by notchjpl** [wgebis/terraform-provider-mailgun#50]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

1.5.3

### Affected Resource(s)
Please list the resources as a list, for example:
- mailgun_domain

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

 count = local.use_mailgun && local.use_cloudflare ? length(data.mailgun_domain.mailgun_domain[0].sending_records):0 

### Expected Behavior
Have the sending_records to create the validation DNS

### Actual Behavior
Either if I use the data or the resource, I cant use it in the count as terraform complaints because it needs to create the resources before getting the output

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The very same works for other cases, like creating the ssl validation records:

  count = local.use_cloudflare ? length(module.ssl[0].distinct_domain_names) : 0

**Comment by notchjpl** [comment]
The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.

**Comment by Szasza** [comment]
@notchjpl if that helps, the problem can be approached slightly differently. Instead of using `count`, try to use `for_each`. Something along these lines should do the job:

```
resource "mailgun_domain" "this" {
  name = "some.sender.domain

  ...
}

resource "aws_route53_record" "mailgun_sending_record" {
  for_each = merge(flatten([
    for record in mailgun_domain.this.sending_records_set : {
      (record.id) = {
        name    = record.name
        type    = record.record_type
        value   = record.value
      }
    }
  ])...)

  name    = each.value.name
  type    = each.value.type
  zone_id = some.zone.id
  records = [
    each.value.value
  ]
}
```

**Comment by G-Rath** [comment]
This is a limitation with Terraform related to how `count` works, and why we added [`receiving_records_set`](https://registry.terraform.io/providers/wgebis/mailgun/latest/docs/resources/domain#receiving_records_set) to allow using a `for_each` - see #37 and #27 for more details.
