### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by Prior99** [wgebis/terraform-provider-mailgun#6]
Terraform crashes.

### Terraform Version

```
terraform -v                                                                              
Terraform v0.13.5
+ provider registry.terraform.io/hetznercloud/hcloud v1.23.0
+ provider registry.terraform.io/timohirt/hetznerdns v1.1.1
+ provider registry.terraform.io/wgebis/mailgun v0.5.2
```

### Affected Resource(s)

mailgun_domain

### Terraform Configuration Files
```hcl
resource "mailgun_domain" "bitwarden" {
  name   = local.some_name
  smtp_password = var.some_smtp_password
  region = "eu"
}
```

### Debug Output

https://gist.github.com/Prior99/ec77f1ba3e191eefa0658b233e71e2aa

### Panic Output

https://gist.github.com/Prior99/74ee0b905565ca264c920baac236e4fe

### Expected Behavior
Mailgun domain created and terraform doesn't crash

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

Create Terraform configuration with above content and apply with `-target=`

### Important Factoids

Not that I know of.

### References

Not that I know of.

**Comment by wgebis** [comment]
Hi @Prior99 ! Could you try to specify explicitly desired `spam_action` ?

**Comment by nerd0** [comment]
Ran into the same thing...

 Terraform crashes.

### Terraform Version
```
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.14.1
+ provider registry.terraform.io/-/local v2.0.0
+ provider registry.terraform.io/-/rabbitmq v1.4.0
+ provider registry.terraform.io/-/random v3.0.0
+ provider registry.terraform.io/hashicorp/aws v3.14.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/terraform-providers/rabbitmq v1.4.0
+ provider registry.terraform.io/wgebis/mailgun v0.5.2
```
### Affected Resource(s)

### Debug Output
```
module.development.module.<**redacted**>.data.aws_route53_zone.selected: Refreshing state... [id=Z1YZA2GL8AQTKD]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.development.module.<**redacted**>.aws_route53_record.mailgun_receiving_records_mx will be created
  + resource "aws_route53_record" "mailgun_receiving_records_mx" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + records         = (known after apply)
      + ttl             = 300
      + type            = "MX"
      + zone_id         = "<**redacted**>"
    }

  # module.development.module.<**redacted**>.aws_route53_record.mailgun_sending_record_0 will be created
  + resource "aws_route53_record" "mailgun_sending_record_0" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 300
      + type            = (known after apply)
      + zone_id         = "<**redacted**>"
    }

  # module.development.module.<**redacted**>.aws_route53_record.mailgun_sending_record_1 will be created
  + resource "aws_route53_record" "mailgun_sending_record_1" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 300
      + type            = (known after apply)
      + zone_id         = "<**redacted**>"
    }

  # module.development.module.<**redacted**>.aws_route53_record.mailgun_sending_record_2 will be created
  + resource "aws_route53_record" "mailgun_sending_record_2" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 300
      + type            = (known after apply)
      + zone_id         = "<**redacted**>"
    }

  # module.development.module.<**redacted**>.mailgun_domain.new will be created
  + resource "mailgun_domain" "new" {
      + id                = (known after apply)
      + name              = "<**redacted**>"
      + receiving_records = (known after apply)
      + region            = "us"
      + sending_records   = (known after apply)
      + smtp_login        = (known after apply)
      + smtp_password     = (known after apply)
      + wildcard          = true
    }
```
 ### Panic Output

https://gist.github.com/nerd0/5c09bfec9f3c787c0c17eab0d651ca63

### Expected Behavior
 
Mailgun domain created and route53 records created

### Actual Behavior
 
 Terraform crashes.

### Steps to Reproduce
 
Create Terraform configuration with above content and apply with `-target=`

### Important Factoids

### References

**Comment by Prior99** [comment]
@wgebis I did. Doesn't help.

**Comment by wgebis** [comment]
Thanks, I’m not able to reproduce it so far, will let you know guys if I will find the reason.

**Comment by wgebis** [comment]
Hi @Prior99 @nerd0 
I found the reason, it came from the Mailgun API upgrade and it's related to reaction API creation endpoint of passing trivial SMTP password. In that case, the domain object is created, but the default SMTP credential is not created. 
So the workaround is: removing the created object from Mailgun web, set strong `smtp_password` or leave the field empty and perform creation of the desired object.
Let me know if does it help. 
New Mailgun API version has many breaking changes, so the upgrade the provider might take a while 🤔 .

**Comment by wgebis** [comment]
Regardless above I pushed a new hotfix release v0.5.3, it contains a possible fix for the error handling, let me know @Prior99 @nerd0  if it helps. Thanks!

**Comment by nerd0** [comment]
> Regardless above I pushed a new hotfix release v0.5.3, it contains a possible fix for the error handling, let me know @Prior99 @nerd0 if it helps. Thanks!

@wgebis apologies for the delay in response. Took your advice and left the password blank and updated the version, works like a charm now!!! Thanks for the quick turn around!!

**Comment by Prior99** [comment]
I can check this out later. Thanks for the fix. The password that I was trying to set was not trivial, but I guess it had perhaps something to do with the Domain not being verified. Leaving the field blank is not an option as I have to make sure the same password is used in other places. Thanks for your work, though :)
